### ISSUE TITLE
How to edit Queue of player? and next , previous option

### ISSUE THREAD

**Issue by onkarios** [tumtumtum/StreamingKit#395]
How can we edit queue of running player? What is the way to forward song?

**Comment by diegostamigni** [comment]
I'll add some API to manage the queue.

**Comment by tumtumtum** [comment]
FYI. 

The idea of the queue was to support gapless playback. Supporting random access on this queue would be difficult and mess with "complex" threading and buffering code. 

An audio player with support for random access play list management should be a wrapper around STK rather than a feature. There are different concerns when managing playlist-style playback.

**Comment by tumtumtum** [comment]
A general high level player with play lost management as a sample app would probably be a good idea.

**Comment by diegostamigni** [comment]
Cool 👍
