### ISSUE TITLE
Unable to retrieve audio suffix

### ISSUE THREAD

**Issue by ShiChenZhi** [tumtumtum/StreamingKit#419]
[STKLocalFileDataSource audioFileTypeHintFromFileExtension:self->currentUrl.pathExtension]

self->currentUrl is nil

**Comment by ShiChenZhi** [comment]
And when playing MP4 audio, the total time acquired is inaccurate.

**Comment by tumtumtum** [comment]
If a file is VBR the total time of a file is calculated from the average bitrate and number of bytes in the file. In order to know the ABR the file has to be played for a few seconds...the longer you play the better the estimate. Obviously for local files you could read metadata that has the file length or scan the entire file ahead of time. StreamingKit is optimized for streaming audio over a network where the file length is provided OOB.

**Comment by keba76** [comment]
Add my two cents. There is an additional technique for how to retrieve the exact duration. In most cases it works.
Your need retrieve packet duration and packets count. These two values can be obtained in the  handlePropertyChangeForFileStream:(AudioFileStreamID)inAudioFileStream fileStreamPropertyID:(AudioFileStreamPropertyID)inPropertyID ioFlags:(UInt32*)ioFlags {
......
case kAudioFileStreamProperty_DataFormat:
entryToUpdate->sampleRate = entryToUpdate->audioStreamBasicDescription.mSampleRate;
                entryToUpdate->packetDuration = entryToUpdate->audioStreamBasicDescription.mFramesPerPacket / entryToUpdate->sampleRate;
.....
case kAudioFileStreamProperty_ReadyToProducePackets:
UInt64 audioDataPacketCount;
            UInt32 byteCountSize = sizeof(audioDataPacketCount);
            OSStatus error = AudioFileStreamGetProperty(inAudioFileStream, kAudioFileStreamProperty_AudioDataPacketCount, &byteCountSize, &audioDataPacketCount);
currentlyReadingEntry->packetCount = audioDataPacketCount; 
When you need duration: 
if (packetCount > 0.0 && packetDuration > 0.0) {
        duration = packetCount * packetDuration;
    } else {
  //otherwise use the usual method in library -(double) duration;
}


}

**Comment by diegostamigni** [comment]
Closing this issue as it isn't really an issue.
