### ISSUE TITLE
shuffle 

### ISSUE THREAD

**Issue by tariqul000** [tumtumtum/StreamingKit#427]

**Comment by iDevelopper** [comment]
**??????????????????????????????????????????????**
Please use proper English to state your issue clearly.
**??????????????????????????????????????????????**

**Comment by tumtumtum** [comment]
In all seriousness, shuffle won't be supported because StreamingKit is a lower level API for managing gapless playback, pre-buffering, HTTP. I've always thought there should be a higher level wrapper with support for standard media playback features such as playlists, shuffle etc but that's not on the roadmap. Many media player apps that use StreamingKit tend to have their own very tailored implementation of playlists so I'm not sure how useful it would be beyond use as a sample app.
